language: scala
scala:
- 2.10.4
jdk:
- oraclejdk7
script:
- sbt compile
deploy:
  provider: heroku
  api_key:
    secure: L7sDTntbWJ2FR6Xn0vHfwsdMze0/e8XtztCCwOB3icB1OksX7VWLLZCgctuB2Ph+19nBvE8r3eDB7l4It72D2BT3UD43fxbRqD7iNmXb8SCNK+l+eGHx7MsEhqGK1g0gRSvz1QyK1ecZVI4sLKu2hH6VJHZJT5p0gT/szY3Q9gw=
  app: dry-fjord-9884
  on:
    repo: numa08/numa08
