#!/bin/bash
#
# Version 0.9
#
# chkconfig : - 80 20
# description: numa08_net is my portal web site

#### Application Specify Configuration
app_name="numa08_net"
app_home="/usr/local/etc/${app_name}"
pid_path="${app_home}/tmp/pids"
app_pid_file="${pid_path}/numa08_net.pid"
app_start_script="${app_home}/target/universal/stage/bin/${app_name}"

#### Application Run COnfiguration
run_arg_port="-Dhttp.port=10008"
run_arg_pid="-Dpidfile.path=${app_pid_file}"

app_pid=0

check_pids(){
  if ! mkdir -p "${pid_path}"; then
    echo "Could not create the path ${pid_path} needed to store the pids."
    exit 1
  fi
  if [ -f "${app_pid_file}" ]; then
    app_pid=$(cat "${app_pid_file}")
  else
    app_pid=0
  fi
}

check_app(){
  if ! [ -f "${app_start_script}" ];then
    echo  "Counld not find application run script at ${app_start_script}."
    echo  "Please run \"cd ${app_home}; play clean stage\""
    exit 1
  fi
}

start(){
  check_pids
  check_app
  echo -n "Startting ${app_name}"

  sh ${app_start_script} ${run_arg_port} ${run_arg_pid} 2>&1 &
  local retval=$?
  if [[ $retval == 0 ]];then
    echo -e "\t\t [\033[1;32m  OK  \033[0m]"
  else
    echo -e "\t\t [\033[1;31m  FAILED  \033[0m]"
  fi

  return $retval
}

stop(){
  check_pids
  echo -n "Stopping ${app_name}"
  local retval=0
  if [[ ${app_pid} > 0 ]];then
    kill -15 ${app_pid}
    echo -e "\t\t [\033[1;32m  OK  \033[0m]"
    retval=0
  else
    echo -e "\t\t [\033[1;31m  FAILED  \033[0m]"
    retval=1
  fi

  return $retval
}

status(){
  check_pids

  if [[ ${app_pid} > 0 ]];then
    echo "${app_name} (pid ${app_pid} ) is runnning..."
  else
    echo "${app_name} is stopping"
  fi
}
  
RETVAL=0
case "$1" in
  start)
    start
    RETVAL=$?
    ;;
  stop)
    stop
    RETVAL=$?
    ;;
  status)
    status
    RETVAL=$?
    ;;
  restart)
    stop
    start
    RETVAL=$?
    ;;
  *)
    echo "Usage ${app_name} : (start | stop | status | restart)"
    RETVAL=2
esac

exit ${RETVAL}
